name: Test
on:
  push:
    branches:
      - development
    tags:
      - "*"
  pull_request:

env:
  go_version: "~1.14.3" # 1.14.x

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go_version }}

      - name: Setup env
        shell: bash
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run unit tests
        run: |
          go test ./...
